#!/usr/bin/env python
#file:load_jquery

def main():
	with open('static/jquery2.2.3.min.js','r') as f:
		jquery = f.read()
	print 'content-type:text/html\n'
	print jquery
		
if __name__ == '__main__':
	main()